### ISSUE TITLE
Copter params not written when updated

### ISSUE THREAD

**Issue by zlite** [diydrones/apm_planner#167]
We're finding that the params are not being written to the autopilot after they are changed. Tested on Mac with Pixhawk and Copter 3.1.1rc2

**Comment by dewoodruff** [comment]
I'm having the same problem with SR0 not staying set and therefore I can't use my minimosd. I've been researching and trying things for days. Based on the console output I think I've tracked the problem back to the USB MAVLINK connection resetting the parameters back! 

I see in the console the modified settings are written and confirmed back as expected:
`
INFO MissionPlanner.MAVLinkInterface - setParam 'SR0_RC_CHAN' = '5' sysid 1 compid 1
INFO MissionPlanner.MAVLinkInterface - setParam gotback SR0_RC_CHAN : 5
INFO MissionPlanner.MAVLinkInterface - setParam 'SR0_POSITION' = '2' sysid 1 compid 1
INFO MissionPlanner.MAVLinkInterface - setParam gotback SR0_POSITION : 2
INFO MissionPlanner.MAVLinkInterface - setParam 'SR0_EXTRA1' = '5' sysid 1 compid 1
INFO MissionPlanner.MAVLinkInterface - setParam gotback SR0_EXTRA1 : 5
INFO MissionPlanner.MAVLinkInterface - setParam 'SR0_EXTRA3' = '3' sysid 1 compid 1
INFO MissionPlanner.MAVLinkInterface - setParam gotback SR0_EXTRA3 : 3
INFO MissionPlanner.MAVLinkInterface - setParam 'SR0_EXTRA2' = '2' sysid 1 compid 1
INFO MissionPlanner.MAVLinkInterface - setParam gotback SR0_EXTRA2 : 2`

But then a few seconds later, they are overwritten!
`
INFO MissionPlanner.MAVLinkInterface - Request stream EXTENDED_STATUS at 2 hz for 1
INFO MissionPlanner.MAVLinkInterface - Request stream EXTRA3 at 2 hz for 1
INFO MissionPlanner.MAVLinkInterface - Request stream RAW_SENSORS at 2 hz for 1
INFO MissionPlanner.MAVLinkInterface - Request stream RC_CHANNELS at 2 hz for 1
`

If I change the settings, then very quickly after they are written click disconnect, the minimosd works perfectly!

But the next time I connect APM to either APM Planner 2 or Mission Planner, the settings are overwritten again. Resetting the settings everytime I plug into USB is obviously not a solution but perhaps this will help point the developers in the write direction. 

I'd be fine with an option to disable USB MAVLINK since I don't use it and don't care. Does that exist?

**Comment by dewoodruff** [comment]
And after reading a little more, it seems that is because Arducopter shares SR0 with USB and telemetry. APM Planner and Mission Planner need one set of settings for USB telemetry, and the minimosd needs a different set. The software overwrites anything that is configured since it is connected.

**Comment by billbonney** [comment]
Use Telem2 or other port for OSD, or have the osd set the settings on startup.

**Comment by dewoodruff** [comment]
Thanks. Unfortunately with the APM there is no telem2 and the minimosd can't push settings like that as far as I can tell. I'll direct anything else to the forums. Thanks.
