### ISSUE TITLE
Error compiling with Qt5

### ISSUE THREAD

**Issue by froller** [diydrones/apm_planner#497]
g++ -c -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -O2 -D_REENTRANT -Wall -W -fPIE -DQ_LINUX_64 -D_TTY_NOWARN_ -D__STDC_LIMIT_MACROS -DGIT_COMMIT=2.0.15-rc3-26-gda80ece -DGIT_HASH=da80ecefc008196b76677f70037a5a551823aad0 -DQT_NO_DEBUG -DMAVLINK_NO_DATA -DQGC_USE_ARDUPILOTMEGA_MESSAGES -DNOMINMAX -DEXTERNAL_USE -DDATADIR=\"/share\" -DPKGDATADIR=\"\" -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_WEBKIT_LIB -DQT_WIDGETS_LIB -DQT_TESTLIB_LIB -DQT_SCRIPT_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR=\"/home/froller/git/apm_planner\" -I/usr/lib64/qt5/mkspecs/linux-g++-64 -I. -IQsLog -isystem /usr/include -isystem /usr/local/include -Ilibs/mavlink/include/mavlink/v1.0 -Ilibs/mavlink/include/mavlink/v1.0/ardupilotmega -Isrc/apps/mavlinkgen -Isrc/apps/mavlinkgen/ui -Isrc/apps/mavlinkgen/generator -Ilibs/eigen -Ilibs/alglib -Ilibs/opmapcontrol/src/core -Ilibs/opmapcontrol/src/internals -Ilibs/opmapcontrol/src/internals/projections -Ilibs/opmapcontrol/src/mapwidget -Ilibs/utils -Ilibs -Ilibs/opmapcontrol -Ilibs/qwt -Ilibs/thirdParty/quazip -I/usr/lib64/qt5/src/3rdparty/zlib -I. -Isrc -Isrc/ui -Isrc/ui/linechart -Isrc/ui/uas -Isrc/ui/map -Isrc/uas -Isrc/comm -Iinclude/ui -Isrc/input -Isrc/lib/qmapcontrol -Isrc/ui/mavlink -Isrc/ui/param -Isrc/ui/watchdog -Isrc/ui/map3D -Isrc/ui/mission -Isrc/ui/designer -Isrc/ui/configuration -Isrc/output -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWebKitWidgets -isystem /usr/include/qt5/QtSvg -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWebKit -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtTest -isystem /usr/include/qt5/QtScript -isystem /usr/include/qt5/QtSerialPort -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -Ibuild-release/moc -Ibuild-release/ui -o build-release/obj/QsLogDest.o QsLog/QsLogDest.cpp
In file included from /usr/include/qt5/QtCore/QFile:1:0,
                 from QsLog/QsLogDestFile.h:30,
                 from QsLog/QsLogDest.cpp:28:
/usr/include/qt5/QtCore/qfile.h:100:24: error: missing binary operator before token "("
 #if QT_DEPRECATED_SINCE(5,0)
                        ^
make: *** [build-release/obj/QsLogDest.o] Error 1

**Comment by zwarren** [comment]
Having just run into this on Fedora 21, the original problem reported by froller is caused by having qt4 and qt5 headers installed on the same machine. Unfortunately on Fedora the qt4 headers live in /usr/include/QtCore/... and the qt5 headers live in /usr/include/qt5/QtCore/... The -isystem /usr/include appears before -isystem /usr/include/qt5 in the g++ arguments above. It's ok for QsLogDestFile.h since it includes \<QFile\> which is found in /usr/include/qt5/QtCore/, however qfile.h includes \<QtCore/qfiledevice.h\> and so on, using the \<QtCore/...\> path means the first matching include is /usr/include/QtCore/... which doesn't define QT_DEPRECATED_SINCE.

Easy workaround is to uninstall qt4-headers (sudo yum remove qt4-devel).

**Comment by billbonney** [comment]
if you run `make -query' you will see where the headers are picked up for the build. The issue is likely that the file are in user include in the first place, as make morally manages those dependencies.

**Comment by zwarren** [comment]
> The issue is likely that the file are in user include in the first place

The issue is that qgroundcontrol.pri and QGCExternalLibs.pri explicitly set /usr/include in the INCLUDEPATH variable. When I remove /usr/include from the .pri files the compile is successful, even with qt4-devel package installed.
/usr/include is a default search path anyway so it shouldn't be in the .pri files at all.

**Comment by malcom2073** [comment]
Good catch, verifying that it is not needed and then I'll push a fix removing those include lines.
