### ISSUE TITLE
GoogleSatellites not loaded at some zoom levels

### ISSUE THREAD

**Issue by Smartype** [diydrones/apm_planner#510]
Version: v2.0.15-4c3

For example, at lat 29.8709779°, lon 121.5977579° zoom 13. Even with a VPN connection, GoogleSatellites will not load. All black.
With GoogleHybrid, only the road and road name loads. 
While GoogleMaps and Terrain loads just ok.

But at zoom levels below 13, it just loads ok.
By the way, MissionPlanner is able to load at least to level 18. And I was able to load to level 18 with old version of APM Planner at the same area.

**Comment by HarrisonHeli** [comment]
I am having issues pulling satellite maps down in 2.0.19-rc5 with a zoom greater than 14.
The problem seems to only occur over Melboune, Vic, Australia ?

here is a reference.
https://www.google.com.au/maps/@-37.7946019,144.9905493,13.5z?hl=en

I can get the basic Google map tiles and the hybrid will show the street names
If I move out to remote area away from Melbourne, I can go down to zoom level 20.

Is this a Google problem?

**Comment by billbonney** [comment]
This has been fixed in current master. Google changes there API versions and it breaks the mapping code.

**Comment by billbonney** [comment]
This is an old issue, so closing. We can raise a new one if maps beaks again (as it will) later
