### ISSUE TITLE
SIGABRT kills apm_planner when double clicking on existing waypoint (ubuntu)

### ISSUE THREAD

**Issue by labtoast** [diydrones/apm_planner#571]
There are asserts in waypointItem.cpp:107 that cause apm_planner to quit when double clicking on existing waypoint. I tested this with no vehicles being connected to apm_planner.

Steps to reproduce:
1) start apm_planner
2) double click in map area to drop waypoint
3) double click on existing waypoint

I am on Ubuntu 14.04. On the second double click it should create another waypoint. mapcontrol::WayPointItem::mousePressEvent() is called 3 times. The second and third time the 'text' variable points to the same memory address.

Function that kills app in waypointitem.cpp:107
function: http://pastebin.com/BZ9AmVJF
log: http://pastebin.com/eR7swxCt

**Comment by malcom2073** [comment]
Good find, it seems that mousePressEvent is called twice for a double click before mouseReleased is called, which is crashing due to our waypoint text overlay (when you click-drag a waypoint). Double clicking on a waypoint does not add another waypoint on top of it, however it should also not crash. I'll add in some logic to check for that
