### ISSUE TITLE
Log Export not complete

### ISSUE THREAD

**Issue by billbonney** [diydrones/apm_planner#796]
**keohr** see http://ardupilot.com/forum/viewtopic.php?f=82&t=13600
With recent compiled APM Planner 2.0 (2015-08-27) I get some inconsistent / missing log lines when exporting from bin -> log.

1. 
FMT, 133, 35, RCIN, Ihhhhhhhhhhhhhh, TimeMS,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14
Defined are C1 to C14 but only C1 to C12 are exported:
RCIN, 75375, 1490, 1526, 982, 1520, 1166, 1494, 982, 982, 874, 874, 874, 874
(in this case LogAnalyzer reports BAD LINE:)

2.
The MSG line(s) is -not always- exported:
So sometimes these lines are missing in the export:
FMT, 132, 67, MSG, Z, Message
and for example:
MSG, ArduCopter V3.2.1 (36b405fb)
MSG, PX4: ce602658 NuttX: 475b8c15
MSG, PX4v2 00320030 3034510A 38353334
MSG, Frame: QUAD

3.
The Parameters 
PARM, THR_MIN, 130
PARM, THR_MAX, 1000
and perhaps more are not exported
(LogAnalyzer exits with error)

Hope this will help to improve APM Planner.

**Comment by bolodya75** [comment]
I confirm such behavior.
Farther more... I guess that it is a consequence of a wrong *.bin file reading by APM because:
- C13 and C14 columns from RCIN message are missing in table view even if I just open *.bin file (before Export),
- in my case MSG messages are not readed by APM Planner during *.bin file opening,
- some values are devided by 100 and then rounded till 2 digits. Wrong fields are:
     - GPS: HDop, RelAlt, Alt, Spd, GCrs (all altitudes are arount 0.00...0,02 instead 0...20)
     - ATT: all roll, pitch and yaw angels (I have max 0,45, not 45)
     - CTUN: all altitudes (all altitudes are arount 0.00...0,02 instead 0...20)
     - probably anything else... 

To be sure that it is an APM Planner issue I loaded the same *.bin file to Mission Planner - all values are correct, then exported *.bin to *.log (also in MP). The new log file is displayed well in APM Planner graphs.

I use APM2.5 with ArduCopter 3.2.1, APM Planner 2.0.18 (on ArchLinux) and the last MP (in Virtual box)
