### ISSUE TITLE
Graph: not all Events/error are marked in the log

### ISSUE THREAD

**Issue by AndKe** [diydrones/apm_planner#870]
please see attached log.
only the first event/log are graphed in the log, but there are many more.

[10.BIN.zip](https://github.com/diydrones/apm_planner/files/78516/10.BIN.zip)

**Comment by billbonney** [comment]
@Arne-W Maybe you would like to look at this issue, as I'm a bit busy for the next few days.

**Comment by AndKe** [comment]
I kind of remember enough of that code to have a clue what might be wrong,
will check later today.

**Comment by Arne-W** [comment]
@billbonney I will have a look - hopefully tomorrow

**Comment by AndKe** [comment]
additional info:
it seems only first error shows, and *no* events. another log full of events (none plotted) made by another user is here: https://www.dropbox.com/s/nzo3ds50w2pfii5/16-1-4_15-14-34.zip?dl=0

**Comment by Arne-W** [comment]
At the moment only plotting a graph of events is implemented. The "show EV" button has no effect, it is the next feature on my list :-)
Regarding the error plotting issue the implementation suppresses identical error messages following each other directly to prevent polluting. 
In the 10.bin I found 4 identical error events - so only the first has an arrow.
Perhaps the suppression is not a good solution. I derived it from the mode implementation where it makes sense because there are often repeated mode events.
 I think the best solution could be to use the relations between Mode, Err and EV while plotting - but until then a lot work has to be done :-)

**Comment by AndKe** [comment]
the repeat should be disabled, it can hide important errors and only display one, by only displaying them one, before takeoff.

**Comment by billbonney** [comment]
I don't think we should remove any messages from the log, including mode changes as they are indicative of an issue and sometime are there for good reason. I'll look at ArduPilot code and try and understand the extra mode change logging.

**Comment by Arne-W** [comment]
Good idea. But as mentioned above I think the only way is to plot  all Err, Mode and EV messages in one run and handle their relation.
It looks like the relation between those messages show which of them can be suppressed because their content is redundant.

**Comment by AndKe** [comment]
Works great, I like the use of colours.
would you please add MSG messages (strings) in the same way ?  very useful for planes. 
attaching screenshot to illustrate the kind of data we would see. 
(please say so if you wish this feature request as a new issue)
![screenshot from 2016-02-06 20-27-11](https://cloud.githubusercontent.com/assets/1468842/12868850/22c90b94-cd10-11e5-8888-8f765aaf2bf0.png)

**Comment by Arne-W** [comment]
Nice to hear you like it :-)
Should not be a problem to realize this. It would be great if you could open a new issue for this as it becomes more transparent who is working on which features then. 

@billbonney If AndKe creates a new issue you can assign it to me.

**Comment by AndKe** [comment]
https://github.com/diydrones/apm_planner/issues/898 created.   :)
